export const League = {
  KBO: "KBO",
  FUTURES: "FUTURES",
  UNKNOWN: "UNKNOWN",
};

export const stadiums = [
  {
    signBoard: "서울종합운동장 야구장",
    code: "SOJ",
    teamColor: "bg_team_dsb_lgt",
    lat: 37.512,
    lon: 127.071,
    league: League.KBO,
  },
  {
    signBoard: "수원 케이티 위즈 파크",
    code: "SKW",
    teamColor: "bg_team_ktw",
    lat: 37.299,
    lon: 127.01,
    league: League.KBO,
  },
  {
    signBoard: "인천 SSG 랜더스필드",
    code: "ILF",
    teamColor: "bg_team_ssg",
    lat: 37.436,
    lon: 126.693,
    league: League.KBO,
  },
  {
    signBoard: "창원 NC 파크",
    code: "CNP",
    teamColor: "bg_team_ncd",
    lat: 35.222,
    lon: 128.582,
    league: League.KBO,
  },
  {
    signBoard: "광주-기아 챔피언스 필드",
    code: "GCF",
    teamColor: "bg_team_kat",
    lat: 35.168,
    lon: 126.889,
    league: League.KBO,
  },
  {
    signBoard: "사직야구장",
    code: "BSJ",
    teamColor: "bg_team_ltg",
    lat: 35.193,
    lon: 129.061,
    league: League.KBO,
  },
  {
    signBoard: "대전 한화생명 볼파크",
    code: "DBP",
    teamColor: "bg_team_hhe",
    lat: 36.316,
    lon: 127.431,
    league: League.KBO,
  },
  {
    signBoard: "대구 삼성 라이온즈 파크",
    code: "DSP",
    teamColor: "bg_team_ssl",
    lat: 35.841,
    lon: 128.681,
    league: League.KBO,
  },
  {
    signBoard: "고척 스카이돔",
    code: "SOG",
    teamColor: "bg_team_kwh",
    lat: 37.497,
    lon: 126.867,
    league: League.KBO,
  },
  {
    signBoard: "포항 야구장",
    code: "POH",
    teamColor: "bg_team_ssl",
    lat: 36.007,
    lon: 129.359,
    league: League.KBO,
  },
  {
    signBoard: "청주종합운동장 야구장",
    code: "CJB",
    teamColor: "bg_team_hhe",
    lat: 36.638,
    lon: 127.47,
    league: League.KBO,
  },
  {
    signBoard: "고양 국가대표 야구훈련장",
    code: "GNY",
    teamColor: "bg_team_kwh",
    lat: 37.676,
    lon: 126.742,
    league: League.FUTURES,
  },
  {
    signBoard: "베어스 파크",
    code: "BEP",
    teamColor: "bg_team_dsb",
    lat: 37.332,
    lon: 127.454,
    league: League.FUTURES,
  },
  {
    signBoard: "서산전용연습구장",
    code: "SSN",
    teamColor: "bg_team_hhe",
    lat: 36.823,
    lon: 126.455,
    league: League.FUTURES,
  },
  {
    signBoard: "LG 챔피언스 파크",
    code: "LCP",
    teamColor: "bg_team_lgt",
    lat: 37.229,
    lon: 127.505,
    league: League.FUTURES,
  },
  {
    signBoard: "강화 SSG 퓨처스필드",
    code: "GSF",
    teamColor: "bg_team_ssg",
    lat: 37.636,
    lon: 126.499,
    league: League.FUTURES,
  },
  {
    signBoard: "문경 상무 야구장",
    code: "MGB",
    teamColor: "bg_team_msm",
    lat: 36.647,
    lon: 128.161,
    league: League.FUTURES,
  },
  {
    signBoard: "상동 야구장",
    code: "SDB",
    teamColor: "bg_team_ltg",
    lat: 35.299,
    lon: 128.93,
    league: League.FUTURES,
  },
  {
    signBoard: "삼성 라이온즈 볼파크",
    code: "SLB",
    teamColor: "bg_team_ssl",
    lat: 35.864,
    lon: 128.806,
    league: League.FUTURES,
  },
  {
    signBoard: "기아 챌린저스 필드",
    code: "KCF",
    teamColor: "bg_team_kat",
    lat: 34.991,
    lon: 126.556,
    league: League.FUTURES,
  },
  {
    signBoard: "익산 국가대표 야구훈련장",
    code: "IKN",
    teamColor: "bg_team_ktw",
    lat: 35.967,
    lon: 127.009,
    league: League.FUTURES,
  },
  {
    signBoard: "마산 야구장",
    code: "MSB",
    teamColor: "bg_team_ncd",
    lat: 35.221,
    lon: 128.579,
    league: League.FUTURES,
  },
  {
    signBoard: "울산 문수 야구장",
    code: "UMS",
    teamColor: "bg_team_uws",
    lat: 35.531,
    lon: 129.265,
    league: League.FUTURES,
  },
  {
    signBoard: "알수없는 야구장",
    code: "NAN",
    teamColor: "bg_team_nan",
    lat: 37.549,
    lon: 126.991,
    league: League.UNKNOWN,
  },
];

export function getStadium(code) {
  return (
    stadiums.find((stadium) => stadium.code === code) ??
    stadiums.find((stadium) => stadium.code === "NAN")
  );
}
